"""3-mig

Revision ID: 35411ce46aeb
Revises: bd99edded4a4
Create Date: 2025-07-16 17:51:54.158566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35411ce46aeb"
down_revision: Union[str, None] = "bd99edded4a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("favorites", sa.Column("price", sa.Float(), nullable=True))
    op.alter_column(
        "favorites", "coin_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "tokens", "refresh_token", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "disabled", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "root", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "root", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "disabled", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "tokens", "refresh_token", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("favorites", "coin_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("favorites", "price")
    # ### end Alembic commands ###
