"""4-mig

Revision ID: 808a47b2f20b
Revises: 35411ce46aeb
Create Date: 2025-07-16 20:26:04.675516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808a47b2f20b'
down_revision: Union[str, None] = '35411ce46aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('coin_id', sa.Integer(), nullable=False))
    op.drop_column('favorites', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('favorites', 'coin_id')
    # ### end Alembic commands ###
