"""2_mig

Revision ID: bd99edded4a4
Revises: 4c64779edaad
Create Date: 2025-07-11 22:56:30.163617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd99edded4a4'
down_revision: Union[str, None] = '4c64779edaad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_coin_name_key', 'favorites', type_='unique')
    op.drop_constraint('tokens_refresh_token_key', 'tokens', type_='unique')
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    op.create_unique_constraint('tokens_refresh_token_key', 'tokens', ['refresh_token'])
    op.create_unique_constraint('favorites_coin_name_key', 'favorites', ['coin_name'])
    # ### end Alembic commands ###
